name: Sync Related Tools Section from Gist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GH_PAT }}"

      - name: Update Related Tools in this repo and create PR
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git checkout -b update-related-tools
          python scripts/sync_related_tools.py > repos.txt
          git add README.md
          git commit -m 'Update Related Tools section from Gist' || echo "No changes to commit"
          git push --set-upstream origin update-related-tools
          gh pr create --base main --head update-related-tools --title "Update Related Tools section from Gist" --body "Automated update of the Related Tools section."

      - name: Update Related Tools in other repos and create PRs
        run: |
          while read -r repo; do
            gh repo clone m-c-frank/$repo temp_repo
            cd temp_repo
            git checkout -b update-related-tools
            python ../scripts/sync_related_tools.py
            git add README.md
            git commit -m 'Update Related Tools section from Gist' || echo "No changes to commit"
            git push --set-upstream origin update-related-tools
            gh pr create --base main --head update-related-tools --title "Update Related Tools section from Gist" --body "Automated update of the Related Tools section."
            cd ..
            rm -rf temp_repo
          done < ../repos.txt
