name: Sync Related Tools Section from Gist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install gh

    #   - name: Update Related Tools in this repo and open PR
    #     run: |
    #       git config --global user.name 'GitHub Action'
    #       git config --global user.email 'action@github.com'
    #       python scripts/sync_related_tools.py
    #       git checkout -b related-tools-update
    #       git add README.md
    #       git commit -m 'Update Related Tools section from Gist' || echo "No changes to commit"
    #       git push "https://${{ secrets.GH_PAT }}@github.com/m-c-frank/noteutilsyncer.git" related-tools-update
    #       gh pr create --title "Update Related Tools section from Gist" --body "Automated update of the Related Tools section." --head related-tools-update --base main

      - name: Update Related Tools in other repos and open PRs
        run: |
          while read -r repo; do
            git clone "https://github.com/m-c-frank/$repo.git" temp_repo
            cd temp_repo
            python ../scripts/sync_related_tools.py
            git checkout -b related-tools-update
            git add README.md
            git commit -m 'Update Related Tools section from Gist' || echo "No changes to commit"
            git push "https://${{ secrets.GH_PAT }}@github.com/m-c-frank/$repo.git" related-tools-update
            gh pr create --title "Update Related Tools section from Gist" --body "Automated update of the Related Tools section." --head related-tools-update --base main
            cd ..
            rm -rf temp_repo
          done < ../repos.txt
