name: Sync Related Tools Section from Gist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Sync "Related Tools" section and update other repos
      run: python scripts/sync_related_tools.py

    - name: Push to current repo
      run: |
        git push --force --quiet "https://${{ secrets.GH_PAT }}@github.com/m-c-frank/noteutilsyncer.git" main
      env:
        GH_PAT: ${{ secrets.GH_PAT }}

    - name: Push to other repos
      run: |
        for repo in $(cat gist_related_tools.txt); do
          if [[ $repo != "noteutilsyncer" ]]; then
            git -C $repo push --force --quiet "https://${{ secrets.GH_PAT }}@github.com/m-c-frank/$repo.git" main
          fi
        done
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
