name: Sync Related Tools Section

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Grant execute permission to the script
      run: chmod +x ./update_related_tools.sh

    - name: Set up Git for pushing
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'

    - name: Fetch Gist content and update README
      run: ./update_related_tools.sh

    - name: Commit and push if there's a change
      run: |
        git diff --quiet || (git add . && git commit -m "Updated Related Tools section" && git push)
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT }}
