name: Sync Related Tools Section

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Fetch Gist content and update README
      run: ./update_related_tools.sh

    - name: Commit and push if there's a change
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add README.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Updated Related Tools section" && git push)
