name: Sync Related Tools Section from Gist

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Sync "Related Tools" section and get repos list
      run: python scripts/sync_related_tools.py > repos.txt

    - name: Push changes to current repository
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add README.md
        git commit -m 'Update Related Tools section from Gist' || echo "No changes to commit"
        git push --force --quiet "https://${{ secrets.GH_PAT }}@github.com/m-c-frank/noteutilsyncer.git" main

    - name: Push changes to other repositories
      run: |
        while read repo; do
          git clone "https://github.com/m-c-frank/$repo.git"
          cd $repo
          cp ../README.md .
          git add README.md
          git commit -m 'Update Related Tools section from Gist' || echo "No changes to commit for $repo"
          git push --force --quiet "https://${{ secrets.GH_PAT }}@github.com/m-c-frank/$repo.git" main
          cd ..
        done < repos.txt
