name: Sync Related Tools Section from Gist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
env:
    GH_TOKEN: ${{ secrets.GH_PAT }}
jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GitHub CLI
        run: sudo apt-get install gh

      - name: Fetch list of repositories
        run: python noteutilsyncer/fetch_gist_repos.py

      - name: Clone and update each repository
        run: |
          current_repo="$(basename "$GITHUB_REPOSITORY")"
          while read -r repo; do
            if [ "$repo" != "$current_repo" ]; then
              echo "Processing $repo"
              git clone "https://github.com/m-c-frank/$repo.git" $repo
              cd $repo
              python ../noteutilsyncer/update_readme.py
              cd ..
            else
              echo "Skipping current repo: $repo"
            fi
          done < repos.txt
                
      - name: Process repositories
        run: |
              while read -r repo; do
                cd $repo
      
                # 1. Check for changes
                if git diff --exit-code; then
                  echo "No changes to commit for $repo"
                  cd ..
                  continue
                fi
      
                # 2. Set Git user configurations
                git config user.email "relatedworkupdater@github.com"
                git config user.name "Related Work Updater"
      
                # 3. Commit and push
                git checkout -b related-tools-update
                git commit -am 'Update Related Tools section from Gist'
                git push --force "https://${{ secrets.GH_PAT }}@github.com/m-c-frank/$repo.git" related-tools-update
      
                # 4. Check for existing PR
                PR_EXISTS=$(gh pr list --base main --head related-tools-update | wc -l)
                if [ "$PR_EXISTS" -ne "0" ]; then
                  echo "A pull request for branch 'related-tools-update' into branch 'main' already exists for $repo"
                  cd ..
                  continue
                fi
      
                # 5. Create PR
                gh pr create --title "Update Related Tools section from Gist" --body "Automated update of the Related Tools section." --head related-tools-update --base main
      
                cd ..
              done < repos.txt
              - name: Cleanup cloned repositories
        run: |
            while read -r repo; do
            rm -rf $repo
            done < repos.txt
