name: Sync Related Tools Section from Gist

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Sync "Related Tools" section and update other repos
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: ./scripts/sync_related_tools.sh
